DELETE {
  GRAPH <http://example.org/1234/data> {
    ?s ?p ?o
  }
}
WHERE {
  GRAPH <http://example.org/1234/data> {
    ?s ?p ?o
  }
};
INSERT DATA {
  GRAPH <http://example.org/1234/data> {
    <http://example.org/1234> a <http://example.org/vocab#Book2>
  }
}

