---
user-agent: SOCH-fetch 0.3
api keys:
    soch: SOCH_API_key
    ugc: UGC_API_key
page size: 500
redis:
    server: 'localhost:6379'
    triples: 3
prefixes:
    bio: 'http://purl.org/vocab/bio/0.1/'
    context-supertype: 'http://kulturarvsdata.se/resurser/ContextSuperType#'
    context-type: 'http://kulturarvsdata.se/resurser/ContextType#'
    continent: 'http://kulturarvsdata.se/resurser/aukt/geo/continent#'
    country: 'http://kulturarvsdata.se/resurser/aukt/geo/country#'
    county: 'http://kulturarvsdata.se/resurser/aukt/geo/county#'
    crm-archaeo: 'http://www.ics.forth.gr/isl/CRMarchaeo/'
    crm-sci: 'http://www.ics.forth.gr/isl/CRMsci/'
    crm: 'http://www.cidoc-crm.org/cidoc-crm/'
    dc: 'http://purl.org/dc/elements/1.1/'
    dcterms: 'http://purl.org/dc/terms/'
    entity-supertype: 'http://kulturarvsdata.se/resurser/EntitySuperType#'
    entity-type: 'http://kulturarvsdata.se/resurser/EntityType#'
    fmis: 'http://kulturarvsdata.se/raa/fmi/'
    foaf: 'http://xmlns.com/foaf/0.1/'
    geo: 'http://www.opengis.net/ont/geosparql#'
    geofeat: 'http://www.mindswap.org/2003/owl/geo/geoFeatures20040307.owl#'
    georss: 'http://www.georss.org/georss'
    gml: 'http://www.opengis.net/gml'
    libris-author: 'http://libris.kb.se/resource/auth/'
    libris-work: 'http://libris.kb.se/resource/bib/'
    license: 'http://kulturarvsdata.se/resurser/License#'
    municipality: 'http://kulturarvsdata.se/resurser/aukt/geo/municipality#'
    owl: 'http://www.w3.org/2002/07/owl#'
    parish: 'http://kulturarvsdata.se/resurser/aukt/geo/parish#'
    pres: 'http://kulturarvsdata.se/presentation#'
    province: 'http://kulturarvsdata.se/resurser/aukt/geo/province#'
    rdf: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'
    rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
    soch: 'http://kulturarvsdata.se/ksamsok#'
    time: 'http://www.w3.org/2006/time#'
    xml: 'http://www.w3.org/XML/1998/namespace'
    xsd: 'http://www.w3.org/2001/XMLSchema#'
ugc predicates:
    sameAsWikipedia: 'http://kulturarvsdata.se/ksamsok#isDescribedBy'
    